name: Validación Web

on:
  push:
    branches:
      - desarrollo  # Solo se ejecuta en la rama desarrollo

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
